language: node_js
node_js:
  - lts/dubnium
cache:
  directories:
    - node_modules
  yarn: true
install: yarn install --pure-lockfile
script:
  - yarn run lint
  - yarn run build
  - yarn run ganache-cli --gasLimit 8000000 > /dev/null &
  - sleep 5
  - yarn run test:truffle

notifications:
  kleros:
    slack: 'kleros:Ub8n81EgKJ3iRrMDyWyQIVJp'
